### ISSUE TITLE
New release is needed for Krew 

### ISSUE THREAD

**Issue by sterchelen** [iovisor/kubectl-trace#189]
Hi,
The latest krew release of kubectl-trace uses the `v0.1.2` tag. This version has some inconsistencies:

1. In the Makefile, bpftrace version is set to `v0.11.1` whereas in the Dockerfile it is set to `v0.13.0` which is overridden by the Makefile variable.
https://github.com/iovisor/kubectl-trace/blob/fd68b1c1bf614a7213c9834673eb8813c809b036/Makefile#L29
https://github.com/iovisor/kubectl-trace/blob/fd68b1c1bf614a7213c9834673eb8813c809b036/build/Dockerfile.tracerunner#L1
 Also the new version of bpftrace helps to fix this error
```
/bpftrace/include/clang_workarounds.h:14:10: fatal error: 'linux/types.h' file not found  
```

2. The image name set for the run traces still uses the old one `kubectl-trace-bpftrace` (new image name introduced in b41eb65c3179dd88b3093417dc17e3d132900b76)
`--imagename string            Custom image for the tracerunner (default "quay.io/iovisor/kubectl-trace-bpftrace:fd68b1c1bf614a7213c9834673eb8813c809b036")`

Thx 🙇🏼‍♂️.
